services:
  eureka-peer1:
    build: ../eurekaserver
    container_name: eureka-peer1
    environment:
      SPRING_PROFILES_ACTIVE: peer1
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  eureka-peer2:
    build: ../eurekaserver
    container_name: eureka-peer2
    environment:
      SPRING_PROFILES_ACTIVE: peer2
    ports:
      - "8762:8762"
    networks:
      - eureka-net

networks:
  eureka-net: